name: 'run BiliExp'

on:
  schedule:
    - cron: '0 4 * * *' #中午12:00执行，时间与其他脚本有依赖关系如无必要请勿修改
  watch:
    types: started
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
      with: 
        ref: BiliExp-Actions

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: 配置用户信息(一定要填写secrets)
      run: string='${{ secrets.advconfig }}'; if [ -n "$string" ]; then echo "$string" > ./config/config.json; exit 0; fi; string='${{ secrets.biliconfig }}'; if [ -z "$string" ]; then echo "secrets(biliconfig)未填写"; exit -1; fi; array=(${string}); sed -i "s/账号SESSDATA/${array[0]}/g" ./config/config.json; sed -i "s/账号bili_jct/${array[1]}/g" ./config/config.json; sed -i "s/账号uid/${array[2]}/g" ./config/config.json

    - name: 安装依赖库
      run: |
          sudo -H pip3 install --upgrade setuptools
          sudo -H pip3 install -r requirements.txt

    - name: 执行B站经验脚本BiliExp.py
      run: python3 BiliExp.py
